Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/06/2024
Var
// Seção de Declarações das variáveis 
 cpf: inteiro
 datadenascimento :inteiro
 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Escreva sua data de nascimento: ")
 leia(datadenascimento)
 escreva("Escreva seu CPF: ")
 leia(cpf)

Fimalgoritmo