Algoritmo "divisiveis 33"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/06/2024
Var
// Seção de Declarações das variáveis 
numero : inteiro
controle : inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Numeros de 0 a 5000 divisiveis por 33")
para controle de 1 ate 5000 faca

    se controle % 33 = 0 entao
escreval (controle)
fimse
fimpara

Fimalgoritmo