Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/07/2024
Var
// Seção de Declarações das variáveis 
valor,dobro,terco:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("Informe um valor")
 leia(valor)
 dobro <- valor * 2
 terco <- valor * 3
 
 escreval("o dobro de ",valor," é :",dobro)
 escreval("a terça parte de ",valor," é :",terco)


Fimalgoritmo