Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/06/2024
Var
// Seção de Declarações das variáveis 
va:vetor[1..15] de inteiro
i: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Os 15 primeiros mltiplos de 9")
para i de 1 ate 15 faca
va[i] <- i * 9

escreval("Multiplo numero ",i,":",va[i])

fimpara

Fimalgoritmo