CREATE DATABASE sistema_restaurante;
USE sistema_restaurante;

CREATE TABLE pessoa(
id_pessoa INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(40) NOT NULL,
CPF VARCHAR(15) NOT NULL,
RG INT,
TELEFONE VARCHAR(15),
SITUACAO CHAR(5) NOT NULL
);

CREATE TABLE endereco(
id_endereco INT PRIMARY KEY AUTO_INCREMENT,
RUA VARCHAR(30),
CIDADE VARCHAR(30),
UF CHAR(2) NOT NULL,
CEP VARCHAR(12) NOT NULL,
BAIRRO VARCHAR(30),
SITUACAO CHAR(5) NOT NULL,
id_pessoa INT NOT NULL,
FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa)
);

CREATE TABLE cliente(
id_cliente INT PRIMARY KEY AUTO_INCREMENT,
FIDELIDADE VARCHAR(20),
SITUACAO CHAR(5),
id_pessoa INT NOT NULL,
FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa)
);

CREATE TABLE funcionario(
id_funcionario INT PRIMARY KEY AUTO_INCREMENT,
CARGO VARCHAR(30) NOT NULL,
MATRICULA INT,
ESCALA VARCHAR(10) ,
DATA_INICIO_CONTRATO DATETIME DEFAULT CURRENT_TIMESTAMP,
DATA_FIM_CONTRATO DATETIME DEFAULT CURRENT_TIMESTAMP,
SITUACAO CHAR(5) NOT NULL,
SALARIO DECIMAL(10,2),
id_pessoa INT NOT NULL,
FOREIGN KEY (id_pessoa) REFERENCES pessoa(id_pessoa) 
);


CREATE TABLE pagamento(
id_pagamento INT PRIMARY KEY AUTO_INCREMENT,
PAGAMENTO VARCHAR(30) NOT NULL,
VALOR_TOTAL DECIMAL(10,2) NOT NULL,
DESCONTO INT ,
ACRESCIMO INT,
id_pedido INT NOT NULL,
FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido)
);

CREATE TABLE mesa(
id_mesa INT PRIMARY KEY AUTO_INCREMENT,
CAPACIDADE INT ,
NUMERO INT,
SITUACAO INT NOT NULL,
id_pedido INT NOT NULL,
FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido)
);

CREATE TABLE itens_menu(
id_itens_menu INT PRIMARY KEY AUTO_INCREMENT,
PRATO VARCHAR(40) NOT NULL,
QUANTIDADE INT NOT NULL,
CANCELADO CHAR(1),
id_pedido INT NOT NULL,
FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido)
);

CREATE TABLE pedido(
id_pedido INT PRIMARY KEY AUTO_INCREMENT,
DATA_PEDIDO DATETIME DEFAULT CURRENT_TIMESTAMP,
NUMERO_PEDIDO INT NOT NULL,
SITUACAO CHAR(5) NOT NULL,
id_funcionario INT NOT NULL,
id_cliente INT NOT NULL,
id_mesa INT NOT NULL,
id_itens_mesa INT NOT NULL,
id_pagamento INT NOT NULL,
FOREIGN KEY (id_funcionario) REFERENCES funcionario(id_funcionario),
FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
FOREIGN KEY (itens_menu) REFERENCES itens_menu(id_itens_menu),
FOREIGN KEY (id_mesa) REFERENCES id_mesa(id_mesa),
FOREIGN KEY (id_pagamento) REFERENCES pagamento(id_pagamento)
);

SELECT * FROM pessoa;
SELECT * FROM endereco;
SELECT * FROM cliente;
SELECT * FROM funcionario;
SELECT * FROM mesa;
SELECT * FROM pagamento;
SELECT * FROM itens_menu;
SELECT * FROM pedido;




